services:  
  - type: web  
    name: teldrive  
    env: go  
    plan: free  
    buildCommand: |  
      # Install Task  
      sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b ./bin  
      # Run the complete build sequence  
      ./bin/task ui  
      ./bin/task gen    
      ./bin/task server  
    startCommand: ./bin/teldrive run
