services:  
  - type: web  
    name: teldrive  
    env: docker  
    dockerfilePath: ./Dockerfile  
    plan: free  
    region: oregon  
    envVars:  
      - key: DB_DATA_SOURCE  
        sync: false  
      - key: JWT_SECRET  
        generateValue: true  
      - key: TG_UPLOADS_ENCRYPTION_KEY  
        generateValue: true  
      - key: CACHE_REDIS_ADDR  
        fromService:  
          type: redis  
          name: teldrive-redis  
          property: connectionString  
      - key: SERVER_PORT  
        value: "8080"  
  
databases:  
  - name: teldrive-postgres  
    databaseName: teldrive  
    user: teldrive  
    plan: free  
  
  - name: teldrive-redis  
    plan: free
